apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-microservices
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: kustomize-microservices
  source:
    repoURL: 'https://github.com/cc-metinyavuz/github-actions-sample.git'
    path: kustomize/overlays/production #To use Kustomize with an overlay, point your path to the overlay.
    targetRevision: HEAD
    kustomize:
      namePrefix: production-
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kustomize-spring-microservices
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
