apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-actions-sample-2
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: github-actions-sample-2
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 3
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 10
            httpGet:
              path: /actuator/health/readiness
              port: 8080