apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-actions-sample-2
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: github-actions-sample-2
          resources:
            limits:
              memory: 1250Mi
            requests:
              memory: 1250Mi
          env:
          - name: MEM_TOTAL_MB
            valueFrom:
              resourceFieldRef:
                resource: limits.memory